# Generated by Django 3.0.7 on 2020-10-16 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20201008_2338'),
        ('accounts', '0012_profile'),
    ]

    operations = [
    ]
