# Generated by Django 3.0.7 on 2020-10-16 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_merge_20201016_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='desc',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='game',
            name='title',
        ),
    ]
