# Generated by Django 3.0.7 on 2020-10-26 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20201016_2153'),
        ('accounts', '0014_auto_20201025_1729'),
    ]

    operations = [
    ]
